language: cpp
sudo: false
dist: trusty
matrix:
  include:
    - os: linux
      compiler: g++-4.9
      script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 ../
        - make -j2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake
            - cmake-data
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
